[package]
name = "threadfin"
version = "0.1.0"
edition = "2018"

[dependencies]
crossbeam-channel = "0.5"
num_cpus = "1"
once_cell = "1"

[dev-dependencies]
criterion = "0.3"
futures-timer = "3"
rusty_pool = "0.6"
threadpool = "1"

[[bench]]
name = "pool"
harness = false
