[package]
name = "squad"
version = "0.1.0"
edition = "2018"

[dependencies]
atomic-waker = "1"
crossbeam-channel = "0.5"
log = "0.4"
num_cpus = "1"
once_cell = "1.8"
slab = "0.4"

[dependencies.core_affinity]
version = "0.5"
optional = true
